---
title: "Resume"
---

# Education

University of British Columbia, Vancouver, Canada Completion: June 1st, 2023
Bachelor of Urban Forestry — Minor in Landscape and Recreation Planning

# Publications

*Peer-reviewed publications:*

- List any peer-reviewed publications here.

*Reports:*

- List any non-peer reviewed materials you'd like to share here.

# Conferences & Talks

*Invited Talks*

- If you've been invited to speak in a professional setting, list that here. 

*Conference Presentations*

Zhang, D., & Day, S. D. (2022) Changes in Carbon Storage and Aggregation over Time in Urban Soil Blends on
a University Campus [Abstract]. ASA, CSSA, SSSA International Annual Meeting, Baltimore,
MD. https://scisoc.confex.com/scisoc/2022am/meetingapp.cgi/Paper/145282 [Poster and Abstract]

# Awards & Honors

- List any scholarships, bursaries, etc. 

# Teaching Assistantships

University of British Columbia, Vancouver, BC Fall 2022
Teaching Assistant - Part Time, FRST 201 Forest Ecology

• Independently led weekly laboratory and field sessions on indicator species identification, wetland
plant community establishment, ecological succession, disturbance ecology, and nutrient cycling

• Demonstrated field techniques to conduct vegetation and soil surveys using forestry equipment


University of British Columbia, Vancouver, BC Fall 2022
Teaching Assistant - Part Time, FRST 100 Sustainable Forests

• Graded and provided extensive feedback for research essay assignments on the topic of “Sustainable
Forestry in BC”

# Institutional Service

- Volunteering etc. 
